[project]
site_name = "Cookiecutter PyPackage"

nav = [
  { "Home" = "index.md" },
  { "Tutorial" = "tutorial.md" },
  { "Project Structure" = "project_structure.md" },
  { "GitHub Actions" = "github_actions.md" },
  { "Prompts" = "prompts.md" },
  { "PyPI Release Checklist" = "pypi_release_checklist.md" },
  { "Design Decisions" = "design_decisions.md" },
  { "Troubleshooting" = "troubleshooting.md" },
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to light mode"
